### ISSUE TITLE
Integrate with Angular 6

### ISSUE THREAD

**Issue by mani0608** [mmick66/electrate#3]
I am currently using electron-forge with my angular 6 project. I'm stuck at 
`Preparing to Package Application for arch: x64`
Can you please tell me how do i integrate this with angular 6?

**Comment by mmick66** [comment]
This project is specifically for React and many changes will need to be made in order for it to work with Angular. Please have a look at the tutorial in Medium as linked in the Readme file. The philosophy should be the same and by changing the Babel setting while including the correct Angular rather than React modules you should have it working.
